# Dockerfile for local build image.
ARG FROM

FROM ${FROM}

ARG UID
ARG GID

RUN apk add musl-dev qemu-system-x86_64 docker-cli fakeroot cpio python3 curl && \
    rustup component add clippy

RUN getent group ${GID} 2>&1 >/dev/null || addgroup -g ${GID} build && \
    group_name=$(getent group ${GID} | awk -F : '{print $1}') && \
    getent passwd -u ${UID} || adduser -G ${group_name} -u ${UID} -D build

USER ${UID}:${GID}
