name: easyto-init-release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test-build:
    uses: ./.github/workflows/common.yml
    with:
      version: ${{ github.ref_name }}

  release:
    runs-on: ubuntu-24.04
    needs:
      - test-build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v8
        with:
          name: release
          path: artifacts
      - uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_RELEASE: "${{ contains(github.ref_name, '-pre.') }}"
        with:
          args: artifacts/*.tar.gz
